language: smalltalk
sudo: false

smalltalk:
  - Squeak-trunk
  - Squeak-5.0
  - Squeak-4.6

before_script:
  - cd ../../../
  - pwd
  - mkdir -pv smalltalkCI-master/_builds/albums/
  - cd smalltalkCI-master/_builds/albums/
  - wget https://raw.githubusercontent.com/HPI-SWA-Teaching/SWT16-Project-12/master/albums/blankCover_250.png
  - wget https://raw.githubusercontent.com/HPI-SWA-Teaching/SWT16-Project-12/master/albums/blankCover_500.png
  - pwd
  - ls -lisa
