language: smalltalk
sudo: false

smalltalk:
  - Squeak-trunk
  - Squeak-5.0
  - Squeak-4.6

before_script:
  # Copy albums directory into build directory
  - mkdir -p $SMALLTALK_CI_BUILD
  - cp -R $TRAVIS_BUILD_DIR/albums $SMALLTALK_CI_BUILD/
